language: php
sudo : false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - git submodule --quiet update --init --recursive

install:
  - phpize -v
  - composer selfupdate
  - composer install
  - cd ./vendor/phalcon/zephir/
  - ./unit-tests/ci/before_install.sh
  - ./install-nosudo -c
  - cd ./../../../

script: ./vendor/bin/phpunit --coverage-clover coverage.clover
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: 7.0
